### PR TITLE
Create formatter settings vscode

### PR DESCRIPTION
**Pull request by AdriaGual**
Added the settings for the formatter using vscode.

Need to install also the extension `black formatter` from the extensions tab in vscode

### CODE REVIEW

**Comment by AdriaGual** [comment]
@NomadCHK Check if you need a specific formatter or this one is fine

**Comment by NomadCHK** [comment]
> @NomadCHK Check if you need a specific formatter or this one is fine

Let me suggest rufus, I will send a new PR with the formatting and linting settings, so you can have a look a it.

**Comment by NomadCHK** [comment]
did here #13

**Comment by AdriaGual** [comment]
@NomadCHK Not used to rufus but hey, let's give it a try, why not, loving your contributions! ❤️

**Pull request closed without merging**
