### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by NomadCHK**
Hello,

I've made several significant updates to improve the project:

    Code Refactoring: I've reorganized the codebase by refactoring and renaming classes to create a more structured architecture with a clear separation of concerns. This includes introducing controllers for game and emulator management, which enhances the clarity of the bot's workflow. This restructuring should simplify future development and maintenance, making it easier to integrate new features.

    Issue Fixes: Addressed problems related to name vs. ID discrepancies and improved the first-turn logic in battles. The updated turn-checking logic now correctly identifies when it's the player's turn and if it's the first turn, which prevents potential bugs related to turn sequencing.

    Enhanced Card Handling: Improved the card recognition and data interaction processes. Unused components have been removed to reduce complexity, leading to a more efficient codebase.

    Improved Bot Reliability: Increased wait times before proceeding to the next action to better handle variable game load scenarios. Updated the sequence to retry checking for the "NEXT" and "THANKS" buttons up to five times, which enhances the bot's ability to adapt to transient UI states and reduces errors caused by timing issues.

While there are still some areas that need improvement, I believe these changes significantly enhance the performance and maintainability of the project.

Please help me test these changes and let me know your thoughts. Your feedback and any suggestions are greatly appreciated.

Thank you for your time!

### CODE REVIEW

**Comment by NomadCHK** [comment]
@AdriaGual Please dont merge it yet, still in construction

**Comment by NomadCHK** [comment]
@AdriaGual Please take a look at last commit. Some times the new logic to count cards fails, because it fails to drag the card, it happens most with the right card. I tried to change the start x to + 50 but didn't solve yet. Can you please take a look on that? maybe is the card offset

**Comment by NomadCHK** [comment]
I tried to make some adjustments, but we still have some issues with clicking and dragging to place cards in the benchs.

**Comment by NomadCHK** [comment]
I created a debug window to make it easier for us to debug positions and actions, etc.

**Comment by AdriaGual** [comment]
@NomadCHK My man, first of all, the UI looking amazing!

I did some tests and I need you to upload the image from this function (OK_BUTTON_AFK):

`    def check_rival_afk(self, screenshot):
        self.log_callback("Checking if the rival is AFK...")
        if self.image_processor.check_and_click(
            screenshot, self.template_images.get("OK_BUTTON_AFK"), "OK Button AFK", 0.7
        ):
            return True
        return False
`

The other things look really promising!

**Comment by NomadCHK** [comment]
> @NomadCHK My man, first of all, the UI looking amazing!
> 
> I did some tests and I need you to upload the image from this function (OK_BUTTON_AFK):
> 
> ```
> def check_rival_afk(self, screenshot):
>         self.log_callback("Checking if the rival is AFK...")
>         if self.image_processor.check_and_click(
>             screenshot, self.template_images.get("OK_BUTTON_AFK"), "OK Button AFK", 0.7
>         ):
>             return True
>         return False
> ```
> 
> The other things look really promising!

Done! Thank you. Last commit pushed with image so you can test. Also have some code that I am testing to improve connection management, work in progress

**Comment by AdriaGual** [comment]
@NomadCHK Now the bot works, but I feel that it doesn't try to attack as before and doesn't try to play trainer cards, will keep testing!

**Comment by NomadCHK** [comment]
> @NomadCHK Now the bot works, but I feel that it doesn't try to play trainer cards, will keep testing!

Here's playing trainer cards fine. What problem you had?

**Comment by AdriaGual** [comment]
@NomadCHK A little fix:
in the `app.py` the import:
`from views.main_ui import BotUI`

should be:
`from views.main_ui.bot_ui import BotUI`

**Comment by NomadCHK** [comment]
> [#18 (comment)](https://github.com/AdriaGual/pokemon-pocket-bot/pull/18#issuecomment-2477500675)
> 
> @NomadCHK I feel it was just because I had a lot of cards in my hand.
> 
> Also we should add a drag from the bot to the center for the coin cards (just to throw it), I had it on the try attack method I think but we could move it somewhere else now.
> 
> ```
> # Flip a coin action
>         drag_position((500, 1250), (self.center_x, self.center_y))
> ```
Hi! ok.

> I feel it was just because I had a lot of cards in my hand.:

that is because of wrong drags to place card, i think i broke start x and star y and maybe the card_offset_mapping or bench_positions. Would be nice if can try to fix those, you can use the debug window, but need to activate logs on the actions that check hands (using the debug window as parameter on clicks and drags).

> about the Flip a coin:

 Ok, i will check that. Now i am doing the verify_card_played look the battle log, but the miss drags to place cards are causing problems

**Comment by AdriaGual** [comment]
@NomadCHK Just reporting, with 4 cards, the offset should be a bit less, will try with 70 instead of 75.

`card_offset_mapping = {2: 90, 3: 89, 4: 70, 5: 65, 6: 55, 7: 45, 8: 40}`

image

**Comment by NomadCHK** [comment]
@AdriaGual thank you. on the last commits I add new images to interact with battle log, a new way to verify if card was played, also remake some of flow logic. Please be free to help me test it!

**Comment by NomadCHK** [comment]
If it works well for you, I think we can close this PR, because it's already quite big. The next ones we'll do in smaller parts, I promise! hehehe . Thanks again

**Comment by TerpToke** [comment]
👀👀👀

**Comment by NomadCHK** [comment]
@AdriaGual card_offset_mapping is more refined now. I think i need to keep testing just the 2 and 8 hand sizes situations. But i included long presses on the debug now, and also made easy to export and import debug actions/images if someone want to share debug data..

**Pull request merged**
