### PR TITLE
FIX import app botUI

### PR DESCRIPTION
**Pull request by AdriaGual**

### CODE REVIEW

**Comment by AdriaGual** [comment]
@NomadCHK I did this little fix

**Comment by NomadCHK** [comment]
> @NomadCHK I did this little fix

https://github.com/AdriaGual/pokemon-pocket-bot/commit/ccb1cdf1cdf44f6c13eb83c9559aa70022a1ed89#commitcomment-149160900

> actually the correct is "from views.main_ui import BotUI" as was before....
> because we use the init.py on main_ui. If this is giving error on you side maybe you have a problem on your python path.
> init file:
> 
> 
> // views/main_ui/__init__.py
> from .bot_ui import BotUI
> 
> __all__ = ["BotUI"]
> 
>

**Comment by NomadCHK** [comment]
The import `from views.main_ui.bot_ui import BotUI` bypasses our package structure and shouldn't be used. 

We have specifically set up `views/main_ui/__init__.py` to expose `BotUI` at the package level:

> views/main_ui/init.py
> from .bot_ui import BotUIall = ["BotUI"]

This means the correct import is `from views.main_ui import BotUI`. This:
1. Respects our package's public interface
2. Makes our code more maintainable
3. Protects against future internal restructuring

If you're getting import errors, it's likely due to Python path issues rather than the import statement itself. Please check:
- Your PYTHONPATH includes the project root
- You're running from the correct directory
- All parent directories have `__init__.py` files

**Comment by NomadCHK** [comment]
So, just to make a small update, the latest changes have improved a bit, but the problem still persists when trying to place a card that is too far to the right on the left bench.

**Comment by AdriaGual** [comment]
@NomadCHK I will revert this, I fixed it by creating a __init__.py and adding the import, but maybe everyone should have this?

**Comment by NomadCHK** [comment]
> @NomadCHK I will revert this, I fixed it by creating a **init**.py and adding the import, but maybe everyone should have this?

yes sure, i dont know why init file is not on the PR files. wtf, sorry.
I have a few changes that are not pushed to the last PR, so i will open a new one just to finish sending the last changes here and fix that.

**Comment by NomadCHK** [comment]
was because of gitignore, removing init files from git ignore.

**Comment by NomadCHK** [comment]
done #25

**Comment by AdriaGual** [comment]
@NomadCHK merged

**Pull request merged**
